= SecDim Play Level Builder

It is very easy to make game levels for SecDim Play.
A level is a program with tests suites and runs in a container.

== Step 1: Pre-requisites

Fork and clone this repository.

Install https://docs.docker.com/get-docker/[docker] and https://www.gnu.org/software/make/[make]
and development environment for the language that you are going to
build a level.

== Step 2: Initialise

Run `./build.sh` > init > Choose a language

To get SDK for the language you are building a level.
Currently supported languages are:

`python`, `go`, `typescript`, `javascript`,
`C# (csharp)`, `java`, `solidity`

== Step 3: Create a private repository

Create a private repository on github and clone it.

[source,bash]
----
cd ../
git clone github.com/my-user/my-private-repo
```
----

From SDK copy the `level` directory and `build.sh` to your private
repository.

[source,bash]
----
cp -r ../sdk/level .
cp ../sdk/build.sh .
cd level/
----

== Step 4: Build the level

Each level contains the vulnerable app and two tests suits: usability
and security.

Usability tests are always given to the player,
while security tests, depending on the level difficulty, may not be given.
The player will run `make test` to run usability test suite,
`make securitytest` to run security test suite.

You can find a sample vulnerable app and tests suits in `level` directory.

Start by building the vulnerable app, complete usability test suites
and lastly security tests suites.

. Review the program code in `level/src/` directory.
. Introduce a security bug:
.. You can add a new functionality or modify existing functionalities.
.. Add a usability test for new or modified functionalities.
.. Remember your bug must be a security vulnerability.
.. To get inspired, check out CWE Top 25 Most Dangerous Software Weaknesses or SemGrep Registry
. Add a new security test to test for the security bug:
.. Trivial level: security tests are given to the player.
.. Easy level: security tests are not given. Security test title should be clear: what is tested and asserted.
.. Medium level: security tests are not given. Security test title should give some clue to the player.
.. Hard level: No test output will be shown to the player.
. `make build && make securitytest` to run security tests. They should fail.

*Make sure usability tests always pass.*

== Step 5: Create a patch version

Create a new branch called `patch` and include
a patched version of the vulnerable app.

*The patched version must pass all usability and security tests.*

This patched branch will NOT be provided to the players and
it is only used to verify if level is solvable.

. `git checkout patch` to create a patch branch
. Patch the program
. `make build && make test && make securitytests` to run all tests. They should pass.

== Step 6: Verify

* [ ] `./build.sh` > verify: to verify if everything is okay
* [ ] Update `level/Readme.adoc` (NOT this file!) with a level story/incident, level and any pre-requisites.
* [ ] Remove unnecessary files and directories

== Step 7: Push

git push both master and `patch` branches.

[source,bash]
----
git push
git push -u origin path
----

Add `secdim` as one of the contributers to your private repository.
A friendly SecDim team member will review your level
and will be in touch for the next step.

*Done!*

== Troubleshooting

Ask your question on https://discuss.secdim.com[SecDim Discuss]
