= SecDim Play Level Builder

It is very easy to make game levels for SecDim Play.
A level is a program with tests suites and runs in a container.

== Step 1: Pre-requisites

Fork and clone this repository.

Install https://docs.docker.com/get-docker/[docker] and https://www.gnu.org/software/make/[make]
and development environment for the language that you are going to
build a level.

== Step 2: Initialise

Run `./build.sh`, then select `init` and enter a language, to get the SDK for the language you are going to build a level.

This will create a directory called `level` with
a *sample vulnerable app and test suites*.

Each level contains an app with a security bug and two sets of tests:
usability and security.
Usability tests are always given to the player,
while security tests, depending on the level difficulty, may not be given.

Currently supported languages are:

`python`, `go`, `typescript`, `javascript`,
`C# (csharp)`, `java`, `solidity`

== Step 3: Create a private repository

Create a private repository on github and clone it.

[source,bash]
----
cd ../
git clone github.com/my-user/my-private-repo
----

From SDK copy the `level` directory and `build.sh` to your private
repository.

[source,bash]
----
cp -r ../sdk/level .
cp ../sdk/build.sh .
cd level/
----

== Step 4: Add a security bug

In this task you will modify the sample app to introduce a security bug.

. `make build` To build the app container image.
. `make run` to run the container.
. `make test` to run the usabiity tests.
. `make securitytest` to run security tests.
. `make debug` give a shell from container and maps `src` directory from host to the container.

To begin:

. Review the code in `src/` directory.
. Modify it to introduce a security bug:
.. You can add a new functionality or modify existing functionalities.
.. Add a usability test for new or modified functionalities.
.. Remember your bug must be a security vulnerability.

TIP: Looking for an idea? https://cwe.mitre.org/top25/archive/2022/2022_cwe_top25.html[CWE Top 25] or https://semgrep.dev/r[SemGrep Registry] have sample codes with security bugs.

== Step 5: Add security test(s)

In this task you will add security test(s) to test for the security bug

. `make build && make securitytest` to run security tests. They should fail.

[NOTE]
--
Depending on the level complexity, security tests will be treated differently:

* Trivial: security tests are given to the player.
* Easy: security tests are not given but security test title should be clear as what is being expected.
* Medium: security test title should give some clue.
* Hard: No test output will be shown to the player.
--

== Step 6: Create a patch

In this task you will create a patch for the security bug.

. `git checkout -b patch` to create a patch branch
. Patch the program
. `make build && make test && make securitytests` to run all tests. They should pass.

NOTE: This patched branch will NOT be provided to the players and
it is only used to verify if level is solvable.

== Step 7: Verify

* [ ] `./build.sh` > verify: to verify if everything is okay
* [ ] Update `level/Readme.adoc` (NOT this file!) with a level story/incident, level and any pre-requisites.
* [ ] Remove unnecessary files and directories

== Step 8: Push

git push both master and `patch` branches.

[source,bash]
----
git push
git push -u origin patch
----

Add `secdim` as one of the contributers to your private repository.
A friendly SecDim team member will review your level
and will be in touch for the next step.

*Done!*

== Important notes

. Remember to push both `master` and `patch` branches.
. Usability tests must always pass.
. Security tests must pass in `patch` branch and fail in `master` branch.

== Troubleshooting

Ask your question on https://discuss.secdim.com[SecDim Discuss]
