# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'puma', '~> 7.0.4'
gem 'rack-test'
#gem 'numo-narray'
gem 'numo-narray-alt'
gem 'sqlite3'
gem 'jwt'
gem 'rackup'
gem 'nokogiri'
